version: '3.8'

volumes:
  db-data:
    driver: local

services:
  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskManager_app
    depends_on:
      - db_postgres_15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres_15/taskManager
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8181:8181"

  db_postgres_15:
    image: postgres:15
    container_name: db_postgres
    environment:
      POSTGRES_DB: taskManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5435:5432'
    volumes:
      - db-data:/var/lib/postgresql/data